name: PhpCS
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP Code Style (phpcs)
        uses: chindit/actions-phpcs@master
        with:
          cli: --standard=PSR12
          dir: src/